<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ace</string>
	</array>
	<key>name</key>
	<string>Ace</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\s*)(javascript):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.javascript.filter.ace</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.javascript.filter. ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(coffee):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.coffeescript.filter.ace</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.coffeescript.filter.ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(markdown):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.markdown.filter.ace</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.markdown.filter.ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.md</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.prolog.ace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(! )($|\s.*)</string>
			<key>name</key>
			<string>meta.prolog.ace</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.comment.ace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(//)\s*\S.*$\n?</string>
			<key>name</key>
			<string>comment.line.slash.ace</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(//)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.comment.ace</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1  )</string>
			<key>name</key>
			<string>comment.block.ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.ace</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?===|=|-|~)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#aceline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline-html-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#normal-html-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-ace</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([\w.#_-]*[\w]+)\s*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?!\.|#|\{|\[|=|-|~|/)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{(?=.*\}|.*\|\s*$)</string>
					<key>end</key>
					<string>\}|$|^(?!.*\|\s*$)</string>
					<key>name</key>
					<string>meta.section.attributes.ace</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ace.ace</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#continuation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[(?=.*\]|.*\|\s*$)</string>
					<key>end</key>
					<string>\]|$|^(?!.*\|\s*$)</string>
					<key>name</key>
					<string>meta.section.object.ace</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ace.ace</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#continuation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#aceline</string>
				</dict>
				<dict>
					<key>match</key>
					<string>/</string>
					<key>name</key>
					<string>punctuation.terminator.tag.ace</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.escape.ace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\\.)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=\||')</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>aceline</key>
		<dict>
			<key>begin</key>
			<string>=='|='|==|=|-</string>
			<key>contentName</key>
			<string>source.ace.embedded.ace</string>
			<key>end</key>
			<string>((do|\{)( \|[^|]+\|)?)$|[^\\,]$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.ace.embedded.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ace.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.line.ace.ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Hack to let ace comments work in this context properly</string>
					<key>match</key>
					<string>#.*$</string>
					<key>name</key>
					<string>comment.line.number-sign.ace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ace.ace</string>
				</dict>
			</array>
		</dict>
		<key>continuation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.ace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\\,])\s*\n</string>
		</dict>
		<key>delimited-ace-a</key>
		<dict>
			<key>begin</key>
			<string>=\(</string>
			<key>end</key>
			<string>\)(?=( \w|$))</string>
			<key>name</key>
			<string>source.ace.embedded.ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ace.ace</string>
				</dict>
			</array>
		</dict>
		<key>delimited-ace-b</key>
		<dict>
			<key>begin</key>
			<string>=\[</string>
			<key>end</key>
			<string>\](?=( \w|$))</string>
			<key>name</key>
			<string>source.ace.embedded.ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ace.ace</string>
				</dict>
			</array>
		</dict>
		<key>delimited-ace-c</key>
		<dict>
			<key>begin</key>
			<string>=\{</string>
			<key>end</key>
			<string>\}(?=( \w|$))</string>
			<key>name</key>
			<string>source.ace.embedded.ace</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ace.ace</string>
				</dict>
			</array>
		</dict>
		<key>embedded-ace</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)#{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>source.ace.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ace.ace</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>inline-html-tag</key>
		<dict>
			<key>begin</key>
			<string>^(\s*([\w.#_-]+( [\w.#_-]+=(".*?"))*: )*)([\w.#_-]+( [\w.#_-]+=(".*?"))*:)(?=\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#normal-inline-html-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<key>interpolated-ace</key>
		<dict>
			<key>begin</key>
			<string>=(?=\b)</string>
			<key>end</key>
			<string>\s|\w$</string>
			<key>name</key>
			<string>source.ace.embedded.html</string>
		</dict>
		<key>normal-html-tag</key>
		<dict>
			<key>begin</key>
			<string>([\w.#_-]+=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>normal-inline-html-tag</key>
		<dict>
			<key>begin</key>
			<string>([\w.#_-]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ace</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-id-attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-html-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#normal-html-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-id-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated-ace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ace-a</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ace-b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ace-c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#aceline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-ace</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.ace</string>
	<key>uuid</key>
	<string>4900500C-3839-41F5-BEE5-EEB36023827A</string>
</dict>
</plist>
